/*1) Listar los nombres de todas las tablas del esquema BANK*/
SELECT 	DISTINCT TC.TABLE_NAME
FROM 	INFORMATION_SCHEMA.table_constraints AS TC
WHERE 	TC.TABLE_SCHEMA='bank';										


/*2) Listar las tablas y sus campos claves del esquema BANK*/
/*
SELECT 	TABLE_NAME,
		CONSTRAINT_NAME,
		CONSTRAINT_TYPE,
		TABLE_SCHEMA
FROM 	INFORMATION_SCHEMA.table_constraints;

SELECT 	TABLE_NAME,
		CONSTRAINT_NAME,
		COLUMN_NAME
FROM 	INFORMATION_SCHEMA.KEY_COLUMN_USAGE;

SELECT 	TABLE_NAME,
		CONSTRAINT_NAME,
		COLUMN_NAME
FROM 	INFORMATION_SCHEMA.constraint_column_usage;
*/	 

SELECT	TC.TABLE_NAME,
		COLUMN_NAME
FROM	INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KC
		JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC ON KC.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
WHERE 	TC.TABLE_SCHEMA='bank';	

/*3) Listar las tablas que tienen al menos una clave foranea en el esquema BANK	*/

SELECT	DISTINCT TC.TABLE_NAME 
FROM	INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
WHERE	TC.CONSTRAINT_TYPE ='FOREIGN KEY' AND TC.TABLE_SCHEMA='bank';	


/*4) Listar las tablas que tengan al menos un restriccion tipo CHECK en el esquema BANK */	

SELECT	DISTINCT TC.TABLE_NAME 
FROM	INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
WHERE	TC.CONSTRAINT_TYPE ='CHECK' AND TC.TABLE_SCHEMA='bank';

/*5) Decir cuantos distintos campos de las tablas del esquema BANK estan afectadas por alguna
restriccion(clave foranea, clave primaria,check o indices)*/
SELECT		KC.TABLE_NAME,
			COUNT(KC.COLUMN_NAME)
FROM		INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KC
			JOIN	INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC ON KC.TABLE_NAME=TC.TABLE_NAME
WHERE 	TC.TABLE_SCHEMA='bank'			
GROUP BY 	KC.TABLE_NAME
ORDER BY 	KC.TABLE_NAME ASC; 
